-- The mandir's annual events, exactly as exported from the portal
-- (annual_events.sql, 2026-09-24): these 7 rows and no others.
-- INSERT OR IGNORE keeps it safe if a row with the same id / code exists.

INSERT OR IGNORE INTO "annual_events" ("id", "code", "name", "name_gu", "name_hi", "activity", "activity_gu", "activity_hi", "type", "masa", "paksha", "tithi", "fixed_month", "fixed_day", "overrides_json", "description", "notes", "active", "is_deleted", "created_at", "updated_at") values ('1', 'ANE-001', 'Gujarati New Year (Bestu Varas)', 'બેસતું વર્ષ', '', 'Mataji''s Gadi', 'માતાજીની ગાદી', '', 'TITHI', 'Kartik', 'shukla', '1', '0', '0', '{}', '', '', '1', '0', '2026-09-08 11:20:21', '2026-09-09 08:14:30');
INSERT OR IGNORE INTO "annual_events" ("id", "code", "name", "name_gu", "name_hi", "activity", "activity_gu", "activity_hi", "type", "masa", "paksha", "tithi", "fixed_month", "fixed_day", "overrides_json", "description", "notes", "active", "is_deleted", "created_at", "updated_at") values ('2', 'ANE-002', 'Maha Sud Bij', 'મહા સુદ બીજ', '', 'Mataji''s Dhaja', 'માતાજીની ધજા', '', 'TITHI', 'Magha', 'shukla', '2', '0', '0', '{}', '', '', '1', '0', '2026-09-08 11:20:21', '2026-09-09 08:14:30');
INSERT OR IGNORE INTO "annual_events" ("id", "code", "name", "name_gu", "name_hi", "activity", "activity_gu", "activity_hi", "type", "masa", "paksha", "tithi", "fixed_month", "fixed_day", "overrides_json", "description", "notes", "active", "is_deleted", "created_at", "updated_at") values ('3', 'ANE-003', 'Chaitra Sud Punam', 'ચૈત્ર સુદ પૂનમ', '', 'Mataji''s Ramel', 'માતાજીની રમેલ', '', 'TITHI', 'Chaitra', 'shukla', '15', '0', '0', '{}', '', '', '1', '0', '2026-09-08 11:20:21', '2026-09-09 08:14:30');
INSERT OR IGNORE INTO "annual_events" ("id", "code", "name", "name_gu", "name_hi", "activity", "activity_gu", "activity_hi", "type", "masa", "paksha", "tithi", "fixed_month", "fixed_day", "overrides_json", "description", "notes", "active", "is_deleted", "created_at", "updated_at") values ('4', 'ANE-004', 'Jeth Sud Trij', 'જેઠ સુદ ત્રીજ', '', 'Bhagwan Shri Kamshibapa Sthapana Divas', 'ભગવાન શ્રી કમશીબાપાનો સ્થાપના દિવસ', '', 'TITHI', 'Jyeshtha', 'shukla', '3', '0', '0', '{}', '', '', '1', '0', '2026-09-08 11:20:21', '2026-09-09 08:14:31');
INSERT OR IGNORE INTO "annual_events" ("id", "code", "name", "name_gu", "name_hi", "activity", "activity_gu", "activity_hi", "type", "masa", "paksha", "tithi", "fixed_month", "fixed_day", "overrides_json", "description", "notes", "active", "is_deleted", "created_at", "updated_at") values ('5', 'ANE-005', 'Dussehra', 'દશેરા', '', 'Mataji''s Gadi', 'માતાજીની ગાદી', '', 'TITHI', 'Ashwin', 'shukla', '10', '0', '0', '{}', '', '', '1', '0', '2026-09-08 11:20:21', '2026-09-09 08:14:31');
INSERT OR IGNORE INTO "annual_events" ("id", "code", "name", "name_gu", "name_hi", "activity", "activity_gu", "activity_hi", "type", "masa", "paksha", "tithi", "fixed_month", "fixed_day", "overrides_json", "description", "notes", "active", "is_deleted", "created_at", "updated_at") values ('6', 'ANE-006', 'Dhanteras', 'ધનતેરસ', '', 'Bhagwan Shri Kamshibapa Birthday', 'ભગવાન શ્રી કમશીબાપાનો જન્મદિવસ', '', 'TITHI', 'Ashwin', 'krishna', '13', '0', '0', '{}', '', '', '1', '0', '2026-09-08 11:20:21', '2026-09-09 08:14:31');
INSERT OR IGNORE INTO "annual_events" ("id", "code", "name", "name_gu", "name_hi", "activity", "activity_gu", "activity_hi", "type", "masa", "paksha", "tithi", "fixed_month", "fixed_day", "overrides_json", "description", "notes", "active", "is_deleted", "created_at", "updated_at") values ('7', 'ANE-007', 'P.P. Bhuvaji Shri Sureshbapa Birthday', 'પ.પૂ. ભુવાજી શ્રી સુરેશબાપાનો જન્મદિવસ', '', 'Birthday', 'જન્મદિવસ', '', 'FIXED_DATE', '', '', '0', '9', '27', '{}', '', '', '1', '0', '2026-09-08 11:20:22', '2026-09-09 08:14:31');